// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	"gorm/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/admin/login",
					Handler: AdminLoginHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/goods/:id",
					Handler: GetGoodsByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/goods/create",
					Handler: CreateGoodsHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/goods/delete/:id",
					Handler: DeleteGoodsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/goods/update",
					Handler: UpdateGoodsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/:id",
					Handler: GetUserByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/create",
					Handler: CreateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/user/delete/:id",
					Handler: DeleteUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/user/update",
					Handler: UpdateUserHandler(serverCtx),
				},
			}...,
		),
	)
}
