// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: goodsrpc.proto

package server

import (
	"context"

	"grpc/goodsrpc"
	"grpc/internal/logic"
	"grpc/internal/svc"
)

type GoodsServiceServer struct {
	svcCtx *svc.ServiceContext
	goodsrpc.UnimplementedGoodsServiceServer
}

func NewGoodsServiceServer(svcCtx *svc.ServiceContext) *GoodsServiceServer {
	return &GoodsServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *GoodsServiceServer) CheckGoods(ctx context.Context, in *goodsrpc.CheckGoodsRequest) (*goodsrpc.CheckGoodsResponse, error) {
	l := logic.NewCheckGoodsLogic(ctx, s.svcCtx)
	return l.CheckGoods(in)
}
