// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: pb/goodsrpc.proto

package goodsrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckGoodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int64                  `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckGoodsRequest) Reset() {
	*x = CheckGoodsRequest{}
	mi := &file_pb_goodsrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckGoodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckGoodsRequest) ProtoMessage() {}

func (x *CheckGoodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_goodsrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckGoodsRequest.ProtoReflect.Descriptor instead.
func (*CheckGoodsRequest) Descriptor() ([]byte, []int) {
	return file_pb_goodsrpc_proto_rawDescGZIP(), []int{0}
}

func (x *CheckGoodsRequest) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type CheckGoodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAvailable   bool                   `protobuf:"varint,1,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckGoodsResponse) Reset() {
	*x = CheckGoodsResponse{}
	mi := &file_pb_goodsrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckGoodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckGoodsResponse) ProtoMessage() {}

func (x *CheckGoodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_goodsrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckGoodsResponse.ProtoReflect.Descriptor instead.
func (*CheckGoodsResponse) Descriptor() ([]byte, []int) {
	return file_pb_goodsrpc_proto_rawDescGZIP(), []int{1}
}

func (x *CheckGoodsResponse) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *CheckGoodsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pb_goodsrpc_proto protoreflect.FileDescriptor

const file_pb_goodsrpc_proto_rawDesc = "" +
	"\n" +
	"\x11pb/goodsrpc.proto\x12\bgoodsrpc\".\n" +
	"\x11CheckGoodsRequest\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\x03R\agoodsId\"Q\n" +
	"\x12CheckGoodsResponse\x12!\n" +
	"\fis_available\x18\x01 \x01(\bR\visAvailable\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2W\n" +
	"\fGoodsService\x12G\n" +
	"\n" +
	"CheckGoods\x12\x1b.goodsrpc.CheckGoodsRequest\x1a\x1c.goodsrpc.CheckGoodsResponseB\fZ\n" +
	"./goodsrpcb\x06proto3"

var (
	file_pb_goodsrpc_proto_rawDescOnce sync.Once
	file_pb_goodsrpc_proto_rawDescData []byte
)

func file_pb_goodsrpc_proto_rawDescGZIP() []byte {
	file_pb_goodsrpc_proto_rawDescOnce.Do(func() {
		file_pb_goodsrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_goodsrpc_proto_rawDesc), len(file_pb_goodsrpc_proto_rawDesc)))
	})
	return file_pb_goodsrpc_proto_rawDescData
}

var file_pb_goodsrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_goodsrpc_proto_goTypes = []any{
	(*CheckGoodsRequest)(nil),  // 0: goodsrpc.CheckGoodsRequest
	(*CheckGoodsResponse)(nil), // 1: goodsrpc.CheckGoodsResponse
}
var file_pb_goodsrpc_proto_depIdxs = []int32{
	0, // 0: goodsrpc.GoodsService.CheckGoods:input_type -> goodsrpc.CheckGoodsRequest
	1, // 1: goodsrpc.GoodsService.CheckGoods:output_type -> goodsrpc.CheckGoodsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_goodsrpc_proto_init() }
func file_pb_goodsrpc_proto_init() {
	if File_pb_goodsrpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_goodsrpc_proto_rawDesc), len(file_pb_goodsrpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_goodsrpc_proto_goTypes,
		DependencyIndexes: file_pb_goodsrpc_proto_depIdxs,
		MessageInfos:      file_pb_goodsrpc_proto_msgTypes,
	}.Build()
	File_pb_goodsrpc_proto = out.File
	file_pb_goodsrpc_proto_goTypes = nil
	file_pb_goodsrpc_proto_depIdxs = nil
}
